"use client";
import {useEffect,useRef,useState} from 'react';
import {Mic,Square,Check} from 'lucide-react';
import {parseVoiceArbitrage,VoiceAccount,VoiceArbitrage} from '@/lib/voice-arbitrage';

type SpeechWindow=Window & {SpeechRecognition?:any;webkitSpeechRecognition?:any;ManelVoice?:{version:string;start:(id:string)=>void}};
export function VoiceArbitrageInput({accounts,onApply}:{accounts:VoiceAccount[];onApply:(data:VoiceArbitrage)=>void}){
 const [expanded,setExpanded]=useState(false),[text,setText]=useState(''),[listening,setListening]=useState(false),[message,setMessage]=useState(''),[warnings,setWarnings]=useState<string[]>([]),[mode,setMode]=useState('');
 const recognizer=useRef<any>(null),request=useRef(''),timer=useRef<ReturnType<typeof setTimeout>|null>(null),applied=useRef(false);
 useEffect(()=>{
  function check(){const w=window as SpeechWindow;setMode(w.ManelVoice?'native':w.SpeechRecognition||w.webkitSpeechRecognition?'browser':'keyboard');}
  function received(event:Event){const data=(event as CustomEvent).detail;if(!request.current||data?.id!==request.current)return;request.current='';if(timer.current)clearTimeout(timer.current);setListening(false);if(data.text){setText(value=>(value+'\n'+data.text).trim());setMessage('Fala recebida. Você pode continuar falando ou preencher o formulário.');}else setMessage(data.error==='cancelled'?'Gravação cancelada. Seu texto foi mantido.':data.error||'Não foi possível reconhecer a fala. Tente novamente.');}
  check();window.addEventListener('manel-voice-ready',check);window.addEventListener('manel-voice-result',received);
  return()=>{request.current='';if(timer.current)clearTimeout(timer.current);if(recognizer.current){recognizer.current.onresult=null;recognizer.current.onerror=null;recognizer.current.onend=null;recognizer.current.abort();}window.removeEventListener('manel-voice-ready',check);window.removeEventListener('manel-voice-result',received);};
 },[]);
 function start(){
  const w=window as SpeechWindow;setMessage('');setWarnings([]);
  if(w.ManelVoice){const id=crypto.randomUUID();request.current=id;setListening(true);w.ManelVoice.start(id);timer.current=setTimeout(()=>{if(request.current!==id)return;request.current='';setListening(false);setMessage('A gravação não retornou. Tente novamente ou use o microfone do teclado.');},120000);return;}
  const Recognition=w.SpeechRecognition||w.webkitSpeechRecognition;
  if(!Recognition){setMessage('Neste aparelho, use o microfone do teclado na caixa de texto ou instale o APK com voz.');return;}
  const speech=new Recognition();recognizer.current=speech;speech.lang='pt-BR';speech.continuous=false;speech.interimResults=false;speech.maxAlternatives=1;
  let captured=false,failed=false;setListening(true);
  speech.onresult=(event:any)=>{const phrase=Array.from(event.results as any[]).filter((r:any)=>r.isFinal).map((r:any)=>r[0].transcript).join(' ');if(phrase){captured=true;setText(value=>(value+'\n'+phrase).trim());setMessage('Fala recebida. Continue falando para acrescentar as outras apostas.');}};
  speech.onerror=(event:any)=>{failed=true;setMessage(event.error==='not-allowed'||event.error==='service-not-allowed'?'O acesso à voz foi recusado. Confira a permissão do microfone nas configurações do navegador.':event.error==='no-speech'?'Não ouvi nenhuma fala. Toque no microfone e tente novamente.':event.error==='network'?'O serviço de voz está sem conexão. Tente novamente ou use o microfone do teclado.':'Não foi possível reconhecer a fala. Tente novamente ou use o microfone do teclado.');setListening(false);};
  speech.onend=()=>{setListening(false);if(!captured&&!failed)setMessage('Nenhuma fala recebida. Você pode tentar novamente.');};
  try{speech.start();}catch{setListening(false);setMessage('Não foi possível iniciar o microfone. Tente novamente.');}
 }
 function apply(){if(applied.current)return;const result=parseVoiceArbitrage(text,accounts);setWarnings(result.warnings);if(!result.bets.length){setMessage('Inclua os dados usando “aposta 1”, “aposta 2” e assim por diante.');return;}onApply(result);applied.current=true;setMessage('Formulário preenchido abaixo. Confira conta, seleção, valor e odd antes de salvar.');}
 const first=accounts[0]?accounts[0].house+' '+accounts[0].holder:'Bet365 Manel';
 const second=accounts[1]?accounts[1].house+' '+accounts[1].holder:'Betano Alex';
 return <section className="voice-entry" aria-label="Preenchimento por voz"><button type="button" className="secondary" onClick={()=>setExpanded(v=>!v)} aria-expanded={expanded} disabled={listening}><Mic size={18}/>{expanded?'Ocultar comando de voz':'Preencher por voz'}</button>{expanded&&<div className="voice-body"><p>Diga o evento e o mercado. Para cada aposta, diga o número, a casa e o titular, a seleção, o valor e a odd. Pode falar em partes.</p><details><summary>Ver exemplo de comando</summary><p>Evento Flamengo contra Corinthians. Mercado resultado final. Aposta 1, conta {first}, seleção casa, valor cem reais, odd dois vírgula dez. Aposta 2, conta {second}, seleção fora, valor cem reais, odd dois vírgula dez.</p><p>Para freebet, acrescente: “capital freebet, perda anterior quarenta reais”. Depois escolha o crédito recebido no formulário.</p></details><div className="voice-controls"><button type="button" className="primary" disabled={applied.current||(listening&&mode==='native')} onClick={()=>listening?recognizer.current?.stop():start()}>{listening?<Square size={17}/>:<Mic size={17}/>} {listening?(mode==='native'?'Ouvindo no Android…':'Terminar fala'):text?'Continuar falando':'Começar a falar'}</button></div>{mode==='keyboard'&&<p className="hint">O microfone direto precisa de um navegador compatível ou do APK atualizado. Você também pode ditar com o microfone do teclado.</p>}<label className="field">Texto reconhecido<textarea rows={5} maxLength={12000} value={text} disabled={listening||applied.current} onChange={e=>{setText(e.target.value);setWarnings([]);setMessage('');}} placeholder="Sua fala aparecerá aqui. Você também pode digitar ou corrigir o texto."/></label><p className="hint">A transcrição usa o serviço de voz do aparelho ou navegador. O comando preenche a data que já está no formulário e substitui as apostas deste rascunho. O registro só será salvo quando você confirmar.</p><button type="button" className="secondary" disabled={listening||!text.trim()||applied.current} onClick={apply}><Check size={17}/>{applied.current?'Dados preenchidos':'Preencher formulário para revisar'}</button>{message&&<p role="status" className="voice-message">{message}</p>}{warnings.length>0&&<ul className="voice-warnings">{warnings.map((warning,index)=><li key={index}>{warning}</li>)}</ul>}</div>}</section>;
}
